addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

env:
  - VERSION="7.0" ODOO_REPO="odoo/odoo" EXCLUDE="account_statement_ext_point_of_sale,statement_voucher_killer"
  - VERSION="7.0" ODOO_REPO="OCA/OCB" EXCLUDE="account_statement_ext_point_of_sale,statement_voucher_killer"

  - VERSION="7.0" ODOO_REPO="odoo/odoo" INCLUDE="statement_voucher_killer"
  - VERSION="7.0" ODOO_REPO="OCA/OCB" INCLUDE="statement_voucher_killer"

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - git clone https://github.com/OCA/account-financial-tools ${HOME}/account-financial-tools -b 7.0
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install ofxparse xlrd

script:
  - travis_run_flake8
  - travis_run_tests

after_success:
  coveralls
